### ISSUE TITLE
Непонятное описание kscreenlocker

### ISSUE THREAD

**Issue by mikhailnov** [mikhailnov/gpo-analytics#1]
В https://github.com/mikhailnov/gpo-analytics/blob/8dd403ebdca756ff8e2a5f91c0cee44df0ff11e6/KDE/kscreenlocker.md не понял, Timeout является третьей строкой секции Daemon, то есть полный конфиг выглядит так?

```ini
[Daemon]
Autolock=false
LockOnResume=false
Timeout=60
```

Точно ли timeout в минутах, а не секундах?

В разделе "Допустимые значения" лучше бы явно прописать, что:

* Autolock бывает true/false
* LockOnResume бывает true/false

Также неплохо было бы прописать прямым текстом, какая из двух галок относится к Autolock, а какая к LockOnResume. Догадаться можно, но лучше бы, чтоб не надо было додумывать.

**Comment by VictorR2007** [comment]
Бывает

[Daemon]
Autolock=false
LockOnResume=false

Всё отключено.

Второй вариант, всё работает, автоблокировка чарез 60 мин.

[Daemon]
Timeout=60

Если полностью удалить файл kscreenlockerrc
будут значения по умолчанию.
автоблокирлвка работает, задержка 5 минут.
блокировка осле выхода из ждущего режима работает.

оба параметра отключены.
Нет блокировки по времени.

Прописывать true нигде не нужно.

    Autolock бывает true/false
    LockOnResume бывает true/false

достаточно удалить эти строки вообще.

**Comment by mikhailnov** [comment]
Вот это все в файл бы написать
