### ISSUE TITLE
Приложения по умолчанию

### ISSUE THREAD

**Issue by mikhailnov** [mikhailnov/gpo-analytics#15]
Настройка приложений по умолчанию.

В KDE есть настройка браузера, почтового клиента и т.д. по умолчанию. Не знаю, пишет она в ~/.config/mimeapps.list и/или в другое место. Надо задокументировать, как делать такие настройки.

**Comment by VictorR2007** [comment]
Пишется в два файла.
mimeapps.list и filetypesrc.
Там, если документировать, будет прилично параметров.
Для каждого приложения описывать сразу в два файла вместе?

Типа.
Текстовый редактор по умолчанию.
Файл mimeapps.list
Параметры

application/json=kde5-org.kde.kate.desktop;
application/x-docbook+xml=kde5-org.kde.kate.desktop;
application/x-yaml=kde5-org.kde.kate.desktop;
text/markdown=kde5-org.kde.kate.desktop;
text/plain=kde5-org.kde.kate.desktop;
text/x-cmake=kde5-org.kde.kate.desktop;
application/json=kde5-org.kde.kate.desktop;
application/x-docbook+xml=kde5-org.kde.kate.desktop;
application/x-yaml=kde5-org.kde.kate.desktop;
text/markdown=kde5-org.kde.kate.desktop;
text/plain=kde5-org.kde.kate.desktop;
text/x-cmake=kde5-org.kde.kate.desktop;

Файл filetypesrc
Параметры

embed-application/json=false
embed-application/x-docbook+xml=false
embed-application/x-yaml=false
embed-text/markdown=false
embed-text/plain=false
embed-text/x-cmake=false

**Comment by mikhailnov** [comment]
Давай опишем текстовый редактор, браузер, почтовый клиент. Остальное менее важно, но тоже можно и полезно описать.

**Comment by VictorR2007** [comment]
Блин, ну вот пока начальное состояние описания.

https://github.com/mikhailnov/gpo-analytics/blob/main/KDE/filetypesrc.md

Но когда начал вникать во всё это с приложениями по умолчанию,
оказалось, что на новом пользователе просто нет файлов,
указанных в описании и тут в верхнем сообщении.
Нужно разбираться, как там на самом деле добавляются строки параметров,
если ещё нет таких файлов.
