### ISSUE TITLE
Вертикальные и горизонтальные сетки значков на рабочем столе

### ISSUE THREAD

**Issue by mikhailnov** [mikhailnov/gpo-analytics#17]
Располагать значки горизонтально или вертикально

**Comment by VictorR2007** [comment]
Если в файле ~/.config/plasma-org.kde.plasma.desktop-appletsrc

В секции 

[Containments][40][General]
ToolBoxButtonState=topcenter
ToolBoxButtonX=748

есть параметр
arrangement=1

вот так

[Containments][40][General]
ToolBoxButtonState=topcenter
ToolBoxButtonX=748
arrangement=1

То размещение значков сверху-вниз.

Если параметр
arrangement=1
отсутствует
такая запись

[Containments][40][General]
ToolBoxButtonState=topcenter
ToolBoxButtonX=748

то размещение значков слева направо.

**Comment by VictorR2007** [comment]
Что, сделать такое описание смены размещения значков на рабочем столе?

**Comment by mikhailnov** [comment]
Да, сделай файл `plasma-org.kde.plasma.desktop-appletsrc.md` , и в нем будем постепенно все такое описывать.
