### ISSUE TITLE
История буфера обмена (Klipper)

### ISSUE THREAD

**Issue by mikhailnov** [mikhailnov/gpo-analytics#18]
По умолчанию включен Klipper, но через него могут случайно сохраняться скопированные конфиденциальные данные.

Описать, как минимум, как его выключать. По возможности — как настраивать.

**Comment by mikhailnov** [comment]
И рассмотреть блокировки настройки, чтобы пользователю можно было запретить включать его обратно, если это считается небезопасным.

**Comment by VictorR2007** [comment]
У нас сам приложение Klipper скрыто.
Про него мало кто знает, и оно не запускается, если работает виджет org.kde.plasma.clipboard
Но, например я его использую у себя.
Его можно навсегда выключить через файл
/etc/xdg/klipperrc
с текстом 
[General]
AutoStart=false

Если же в /etc/xdg/klipperrc
указать 
[General]
AutoStart=true

то приложение klipper будет запускаться даже вместе с org.kde.plasma.clipboard

Виджет org.kde.plasma.clipboard полностью заблокировать для всех пользователей вроде невозможно.
Я не смог этого добиться.
Сделаю описание по их параметрам, то что смог нарыть.

**Comment by mikhailnov** [comment]
Видимо, я по ошибке обозвал org.kde.plasma.clipboard  Klipper-ом. Имел в виду виджет буфера обмена по умолчанию.

**Comment by mikhailnov** [comment]
Вместо блокировки, может быть, можно через знак доллара задать, чтоб хранилаясь только одна запись в истории, или чтоб автоматически очищался как-то быстро, если там есть такая функций.

**Comment by VictorR2007** [comment]
> Вместо блокировки, может быть, можно через знак доллара задать, чтоб хранилаясь только одна запись в истории, или чтоб автоматически очищался как-то быстро, если там есть такая функций.


Виджеты включены в plasma-org.kde.plasma.desktop-appletsrc
в строке
[Containments][81][General]
в
extraItems=org.kde.plasma.vault,org.kde.plasma.nightcolorcontrol,org.kde.plasma.mediacontroller,org.kde.kscreen,org.kde.plasma.bluetooth,org.kde.plasma.battery,org.kde.plasma.keyboardlayout,org.kde.plasma.devicenotifier,org.kde.plasma.volume,org.kde.plasma.keyboardindicator,org.kde.plasma.networkmanagement,org.kde.plasma.notifications,org.kde.plasma.manage-inputmethod


Чтобы включить, нужно добавить к перечисленным виджетам ещё и org.kde.plasma.clipboard,
или наоборот его убрать оттуда для отключения.

Я пробовал делать файл
/etc/xdg/plasma-org.kde.plasma.desktop-appletsrc
с указанной выше строкой, но все новые пользователи создают свою строку

[Containments][81][General]
со своим номером, вместо 81.
Я пробовал сделать
[Containments][*][General]
но это не сработало.

**Comment by mikhailnov** [comment]
Думаю, тут разве что через javascript

**Comment by VictorR2007** [comment]
> чтоб хранилаясь только одна запись в истории


А вот так пожалуй можно сделать.
Напишу как можно заблокировать на заданное количество записей в истории.
