### ISSUE TITLE
Настройка сочетаний клавиш

### ISSUE THREAD

**Issue by mikhailnov** [mikhailnov/gpo-analytics#20]
Описать настройку сочетаний клавиш, как минимум:

* переключения раскладок (допустим, что всегда стоят английская и русская раскладка, описывать механизм добавления новых раскладок, думаю, малоприоритетно)
* назначения клавиши compose

На подумать: если повесить переключение раскладки на клавишу win, то сейчас нужно ли удалять alt+f1 из настроек виджета меню приложений?

**Comment by VictorR2007** [comment]
Добавил начальный макет страницы
https://github.com/mikhailnov/gpo-analytics/blob/main/KDE/kxkbrc.md
