### ISSUE TITLE
klipperc: уточнения формулировок

### ISSUE THREAD

**Issue by mikhailnov** [mikhailnov/gpo-analytics#23]
Написано: "Если параметр сихронизации выделения с буфером обмена отключен..."

Нужно немного догадаться, о каком именно параметре идёт речь, также непонятно, чем обусловлена такая необходимость.

Предлагаю сделать список допустимых и недопустимых сочетаний значений двух параметров в виде таблицы. Это позволит разработчику политик и интерфейса настройки понимать, какие сочетания значений нужно разрешать, а какие запрещать.

**Comment by VictorR2007** [comment]
> также непонятно, чем обусловлена такая необходимость.

Ты имеешь ввиду, что нужно указать, для чего может понадобиться отключение синхронизации выделения с буфером обмена ?

**Comment by mikhailnov** [comment]
Вот теперь стало понятно:

![image](https://github.com/mikhailnov/gpo-analytics/assets/15802528/1e0594b4-fdda-4068-8480-66caf71ade89)

Закрываю задачу.
