### ISSUE TITLE
powermanagementprofilesrc: уточнения формулировок

### ISSUE THREAD

**Issue by mikhailnov** [mikhailnov/gpo-analytics#24]
Написано:

"Для полного отключения энергосбережения монитора,

из /etc/xdg/powermanagementprofilesrc должены быть полностью удалены

значения строки параметров
Питание от сети

    [AC][DPMSControl]

Питание от батареи

    [Battery][DPMSControl]

Низкий уровень заряда

    [LowBattery][DPMSControl]
"

Не понял, что это означает. Что в файле не должно быть указанных секций? Или что эти секции должны быть пустыми?

Скорее всего, и так,и так будет работать, но лучше явно прописать.

В разделе "Беспроводные сети' непонятно, что за конфиги. Наверное, имеется в виду, чтт при питании от сети - AC - включать или не выключать wifi и пр.

**Comment by VictorR2007** [comment]
Секции должны быть пустыми.
Сейчас исправлю.
