### ISSUE TITLE
Управление предпросмотром в Dolphin и др. программах KDE

### ISSUE THREAD

**Issue by mikhailnov** [mikhailnov/gpo-analytics#27]
Непроизвольное исполнение кода при обработке изображения или иного файла ялвяется часто встречающимся вектором атаки. Для создания предпросмотра (уменьшенной копии) требуется автоматически обработать изображения в открытом в открытом каталоге. Представляется целесообразным в целях безопасности отключать создание миниюатюр.

Важно задокументировать, как управлять списком форматов для создания миниюатюр и/или полного вкл/выкл создания миниатюр с возможностью запрета включить это пользователю.

**Comment by mikhailnov** [comment]
Еще была вот такая узвимость: https://www.opennet.ru/opennews/art.shtml?num=51235

Возможно, есть настройка, которая позволяет отключить обработку находящихся в папке файлов *.desktop при открытии этой папки.

**Comment by VictorR2007** [comment]
> Еще была вот такая узвимость: https://www.opennet.ru/opennews/art.shtml?num=51235
> 
> Возможно, есть настройка, которая позволяет отключить обработку находящихся в папке файлов *.desktop при открытии этой папки.

В kde5 нет файлов *.desktop

**Comment by VictorR2007** [comment]
> Еще была вот такая узвимость: https://www.opennet.ru/opennews/art.shtml?num=51235
> 
> Возможно, есть настройка, которая позволяет отключить обработку находящихся в папке файлов *.desktop при открытии этой папки.

Там же написано
Исправление будет включено в состав выпуска библиотеки kconfig 5.61.0, который в настоящее время находится на стадии [кандидата в релизы](https://github.com/KDE/kconfig/releases).

У нас версии 5.105.0 и 5.108.0

**Comment by mikhailnov** [comment]
Понятно, что она давно исправлена, это просто пример. desktop-файлы есть в /usr/share/applications/

**Comment by VictorR2007** [comment]
Добавил пока в таком виде
https://github.com/mikhailnov/gpo-analytics/blob/main/KDE/dolphinrc.md

Нужно ли расписать каждый параметр?

Которые в этой строке строке

Plugins=appimagethumbnail,mltpreview,ffmpegthumbs,opendocumentthumbnail,kraorathumbnail,audiothumbnail,imagethumbnail,exrthumbnail,jpegthumbnail,windowsimagethumbnail,svgthumbnail,windowsexethumbnail,comicbookthumbnail,directorythumbnail,textthumbnail,blenderthumbnail,djvuthumbnail,gsthumbnail,cursorthumbnail,fontthumbnail,rawthumbnail,ebookthumbnail,mobithumbnail

**Comment by VictorR2007** [comment]
> Понятно, что она давно исправлена, это просто пример. desktop-файлы есть в /usr/share/applications/

Я сначала не так понял, переклинило.
Посчитал что разговор об .directory
А когда сообразил, то удалил пост.

**Comment by mikhailnov** [comment]
Расписать полезно
