### ISSUE TITLE
Настройка хранителя экрана

### ISSUE THREAD

**Issue by mikhailnov** [mikhailnov/gpo-analytics#7]
Описать настройку хранителя экрана, в документе про энергосбережение (powermanagementprofilesrc) сделать отсылку к нему. Написать так, чтобы незнакомый с KDE человек прочитал и понял, как эта связка настраивается.

**Comment by VictorR2007** [comment]
У нас же уже сделано описание настройки хранителя экрана.
https://github.com/mikhailnov/gpo-analytics/blob/main/KDE/kscreenlocker.md

**Comment by VictorR2007** [comment]
В kde5 нет хранителя экрана.
Есть инструмент блокировки доступа к экрану.
Блокировка экрана включается через 5 минут простоя.
Это инструмент безопасности.
Настройки по умолчанию, от kde, независимы у этих приложений друг для друга.

В настройках энергосбережения, включение потухания экрана тоже через 5 минут простоя.
И полное выключение мониторов через 10 минут.

Это полностью независимые инструменты, с разными задачами,
выполняемыми по разному.

В энергосбережении можно будет указать, что существует инструмент

## Блокировка экрана

### Поведение рабочей среды - Блокировка экрана

**Comment by VictorR2007** [comment]
Посмотри в этом файле, в шапке, достаточно ли такого упоминания,
или переделать по другому
https://github.com/mikhailnov/gpo-analytics/blob/main/KDE/powermanagementprofilesrc.md

Если так достаточно, то закрою эту задачу.

**Comment by mikhailnov** [comment]
Задачу можно закрывать и просто кнопкой в задаче, не обязательно коммитом)
