### ISSUE TITLE
Смена обоев рабочего стола

### ISSUE THREAD

**Issue by mikhailnov** [mikhailnov/gpo-analytics#8]
Часто в корпоративной среде устанавливают фирменные обои. Важно описать, как их устанавливать в KDE. Если нельзя конфигами, то хотя бы запросами по dbus (https://superuser.com/a/1332325) (может, кстати, и панель настраивать можно как-то так?)

**Comment by VictorR2007** [comment]
Это опять же настраивается в файле plasma-org.kde.plasma.desktop-appletsrc

[Containments][58][Wallpaper][org.kde.image][General]
Image=путь к картинке
Не представляю, как это прописывать.
Этот [58] числовой параметр всё ломает.

**Comment by mikhailnov** [comment]
Да скриптом, как по ссылке выше, надо наверняка. Пастор же делал скрипт, но для другой задачи. Пропиши просто формат конфига с пояснением, что число, грубо говоря, произвольное. Если придумаем скрипт, допишем скрипт.

**Comment by VictorR2007** [comment]
Сейчас ещё поразбирюсь, может в другом места получится включить.
