### ISSUE TITLE
улучшить задокументированность блокировок

### ISSUE THREAD

**Issue by mikhailnov** [mikhailnov/gpo-analytics#9]
Читаю https://github.com/altlinux/admx-basealt/blob/master/ru-RU/basealtgsettings.adml . Много упоминаний про блокировку изменения настроек пользователями.

Надо бы для всех настроек, которые описываем, проверить работу блокировок через знак доллара $ и задокументировать их блокируемость. Особенно у касающихся безопасности функций - хранителя экрана и энергосбережения.

**Comment by mikhailnov** [comment]
В https://github.com/mikhailnov/gpo-analytics/blob/main/KDE/kscreenlocker.md нельзя ли заблокировать сразу всю секцию Daemon?

**Comment by VictorR2007** [comment]
> В https://github.com/mikhailnov/gpo-analytics/blob/main/KDE/kscreenlocker.md нельзя ли заблокировать сразу всю секцию Daemon?

Там же написано, в конце «Или же вообще запретить изменение всех параметров»

**Comment by VictorR2007** [comment]
Почти все, ранее сделанные файлы поправил на тему блокировок параметров.
Закрой эту тему.
Следующие описания уже буду делать с более полным описанием блокировок параметров.

**Comment by mikhailnov** [comment]
Ага, стало понятнее, спасибо.
